# -*- coding: utf-8 -*-
"""ml-10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14hsHzm2aw96ypWGgZU8-Vkr2Se7t8cux
"""

import tensorflow as tf

fashion_mnist = tf.keras.datasets.fashion_mnist.load_data()

(x_train_full, y_train_full), (x_test, y_test) = fashion_mnist

split_size = 55000

x_train, y_train = x_train_full[:split_size], y_train_full[:split_size]
x_valid, y_valid = x_train_full[split_size:], y_train_full[split_size:]

x_train, x_valid, x_test, = x_train / 255., x_valid / 255., x_test / 255.

class_names = ["T-shirt/top", "Trouser", "Pullover", "Dress", "Coat", "Sandal", "Shirt", "Sneaker", "Bag", "Ankle boot"]

tf.random.set_seed(42)


def create_model():
    model = tf.keras.Sequential([
        tf.keras.layers.Input(shape=[28, 28]),
        tf.keras.layers.Flatten(),
        tf.keras.layers.Dense(300, activation='relu'),
        tf.keras.layers.Dense(100, activation='relu'),
        tf.keras.layers.Dense(10, activation='softmax')
    ])
    return model


model = create_model()
model.summary()

model.compile(
    loss='sparse_categorical_crossentropy',
    optimizer='sgd',
    metrics=['accuracy']
)

history = model.fit(x_train, y_train, epochs=30, validation_data=(x_valid, y_valid))

x_sample = x_test[:3]
x_sample

y_proba = model.predict(x_sample)
y_proba.round(2)

y_sample = y_test[:3]
y_sample
